# Generated by Django 5.2.5 on 2025-08-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
